### ISSUE TITLE
Unhandled exception in Graph::collapse_graph (GraphHelper.cpp:563)

### ISSUE THREAD

**Issue by pistolero** [vtraag/louvain-igraph#11]
[Here](https://github.com/vtraag/louvain-igraph/blob/master/src/GraphHelper.cpp#L562) there is a check for `total_collapsed_weight` being equal to `this->total_weight`. As they both are floats, check is done by comparing difference to small epsilon (1e-6).

Unfortunately when I'm louvain on the big graph with real weights precision errors accumulate and this comparison fails.

What makes it worse is that it rises C++ exception which is not handled anywhere, and therefore causes core dump to my Python program.

**Comment by vtraag** [comment]
Yes, any `C++` `Exception` should be dealt with more graciously, I agree. This is not only the case here, but throughout the rest of the code as well. Some exceptions are handled, but not all.

Unfortunately equality of floats is a <a href="https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/">persistent problem</a>. If you have a suggestion for how to deal with the situation better, it would be more than welcome. Probably a relative error would be more in order here, given the possible magnitude of the values. However, the accumulation of errors might still pose a problem. Do you have an idea of the size of the difference for your graph? Do you happen to have extremely small/large weights that seem to introduce these kind of errors?

**Comment by pistolero** [comment]
I don't really understand the value of this particular assertion. I think it can be safely removed.

**Comment by vtraag** [comment]
The goal is to ensure that optimisation on the aggregated graph corresponds to optimisation on the original graph. If the difference is negligible, no problem. But if the difference is larger it may indicate that something went wrong somewhere. This may then make the optimisation incorrect. That's why I ask, what is the order of magnitude of the difference?

**Comment by pistolero** [comment]
Difference is small (within 1e-3).

Maybe it is worth to move checks like this to some kind of unit tests?

**Comment by vtraag** [comment]
OK, good to hear that's the difference. Yes, I may move it to only include in when in DEBUG mode. But that sort of difference should probably be sorted out when using relative comparison. Thanks for the report!

**Comment by vtraag** [comment]
Removed the check for now, in future versions, I resort to unit tests as suggested.
