### ISSUE TITLE
Asymptotic Surprise

### ISSUE THREAD

**Issue by ayushidalmia** [vtraag/louvain-igraph#13]
Hi,

Is the quality metric asymptotic surprise also added?

**Comment by vtraag** [comment]
Hi Ayushi,

Yes, the version of Surprise used in the optimisation is the asymptotic version. You can check this also in the <a href="https://github.com/vtraag/louvain-igraph/blob/master/README.md">`README.md`</a>, and should also be mentioned in the Python documentation.

Best,

Vincent

**Comment by ayushidalmia** [comment]
Thanks! I could not understand from the README. :)

**Comment by vtraag** [comment]
No problem, I'll check to see if I can clarify it...
Op 23 nov. 2015 05:57 schreef Ayushi Dalmia <notifications@github.com>:Thanks! I could not understand from the README. :)
