### ISSUE TITLE
Duplicated stdout

### ISSUE THREAD

**Issue by 4knahs** [vtraag/louvain-igraph#17]
A simple python script with:

```
import louvain
print "hello"
```

when executed prints twice:

```
$ python louvain.py
hello
hello
```

Needless to say that it prints normally without the import.

I installed louvain as suggested: `pip install louvain `. 

Have you observed this behavior before? Thanks!

**Comment by vtraag** [comment]
Can't say that I have observed it before. It would be rather surprising if it is specifically related to the `louvain` package. You don't observe the same behaviour with other packages?

I can't reproduce it myself, what OS and what version of python are you running?

**Comment by 4knahs** [comment]
Python 2.7.12 & Ubuntu 16.04. 

I must say i don't use python often but been using other scripts (w/ networkx, sys, itertools...) and they work fine.

**Comment by vtraag** [comment]
Ha, I didn't realise on first reading that you called your script `louvain.py`. You hence import the script itself which prints "hello" and then you execute the second line, which prints "hello" again. The actual package never gets loaded in this way. So rename your file to anything but louvain.py and it should work properly. Let me know if that doesn't work.Op 12 mrt. 2017 19:20 schreef Mário Almeida <notifications@github.com>:Python 2.7.12 & Ubuntu 16.04.
I must say i don't use python often but been using other scripts (w/ networkx, sys, itertools...) and they work fine.

**Comment by 4knahs** [comment]
That is not the case.

A file names os.py:

```
import os
print "hello"
```

```
$ python os.py 
hello
```

Changing the name of the script to anything other than louvain solves nothing unfortunately, but i do agree it is not the best practice.
