### ISSUE TITLE
Reproducibility: option 'random_state'?

### ISSUE THREAD

**Issue by falexwolf** [vtraag/louvain-igraph#19]
Hi!

I've made very good experiences with the package so far, but exact reproducibility of detected communities is an issue for me. Is it possible to fix [srand](http://www.cplusplus.com/reference/cstdlib/srand/) or whatever causes the non-determinism in the algorithm via an option `random_state`, which sets an integer value for the seed (this is the scikit-learn convention). Or something similar?

Thank you very much!
  Alex

**Comment by falexwolf** [comment]
In principle, it seems to be possible to have a reproducible outcome: `igraph.community_multilevel()` is reproducible. :smile:

**Comment by vtraag** [comment]
Hi Alex,

Yes, in principle this is no problem. The option is lacking now, but this is one of those things that is improved in the new implementation.

Best,

Vincent

**Comment by falexwolf** [comment]
I rapidly tried to fix it, but I don't get where the randomness enters. Initialization is done using `membership = range(graph->n_nodes)`, so no randomness here, also in the optimization, the default is to consider all communities `consider_comms = ALL_COMMS`, so again no randomness.

Am I missing something or can I work around this? Is it only happening for `method='RBConfiguration'` and `'Modularity'` or does it pay off trying all methods with all parameters (would take me a while)? Thank you!

**Comment by vtraag** [comment]
No, it relies on the random number generator of different libraries actually internally. When optimising the quality function it iterates over the nodes in a random order. You cannot change this from the Python code, only in the underlying C++ code. If you need this, you should wait for the new implementation (it shouldn't take long anymore).  If you can't wait, drop me a line via mail, and we'll see whether we can get the development version working for you.

**Comment by falexwolf** [comment]
I was going through the underlying C++ code (I'm not a great expert, but I wrote a bunch of things). If you could point me to the part in the code I could possibly come up with a pull request. Or do you think it is going to be hard?

It would be great to have this in the development version.

**Comment by vtraag** [comment]
It already is available in the development version, including the possibility to set the seed state for the random number generator. So, you would be redoing some work, which you'd rather spend actually using the code I imagine. You could also try to checkout the development version yourself and build it, if you are comfortable doing that.

**Comment by falexwolf** [comment]
Ah cool, great! Sorry for the misunderstanding! I'll try to build the development branch and work with that. Thank you very much!

**Comment by vtraag** [comment]
No problem! If you need any help, let me know...

**Comment by vtraag** [comment]
As indicated, this is under development and will be implemented in future versions.
