### ISSUE TITLE
Pip setup on osx crashing

### ISSUE THREAD

**Issue by ktpolanski** [vtraag/louvain-igraph#22]
Hello,

Attempting to install louvain via pip appears to crash, very rapidly and very uninformatively:

	mib111492i:scanpy kp9$ pip install louvain>=0.6
	Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-tlgg517a/louvain/

Setting up from the GitHub source works just fine, mind you. Any idea what may be going on here?

**Comment by vtraag** [comment]
Could you try upgrading `setuptools` and `pip` itself to the latest version?

    pip install --upgrade setuptools

and

    pip install --upgrade pip

**Comment by ktpolanski** [comment]
Upgrading setuptools did the trick, thanks! Still, a bit weird that pip would just fall on its face like that but a from-source install would proceed without a hitch.
