### ISSUE TITLE
Community-detection on weighted graph?

### ISSUE THREAD

**Issue by hao44le** [vtraag/louvain-igraph#23]
Hi,

Can our library run louvain-igraph on the weighted graph?
How do I create a weighted graph on igraph?

Thanks

**Comment by vtraag** [comment]
Yes, the louvain-igraph package is suitable for weighted graph. Please see the [documentation](http://louvain-igraph.readthedocs.io/en/latest/) for further information.

You can easily created weighted graphs in igraph, which also comes with [documentation](http://igraph.org/python/doc/tutorial/tutorial.html).
