### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by falexwolf** [vtraag/louvain-igraph#27]
Dear Vincent,

we have found that installing the current `louvain-igraph` package is difficult on Windows as we couldn't find any `igraph` binary installers for python 3.6. In particular, the ones on https://www.lfd.uci.edu/~gohlke/pythonlibs/ only support python 3.5.

Would it be possible for you to also provide a wheel for louvain version 0.6.1 for python 3.5. on https://pypi.python.org/pypi/louvain - you did this for the previous louvain version? Or do you have an idea where we can find binary installers for igraph that run with python 3.6?

Thank you very much for your help!
  Alex

**Comment by vtraag** [comment]
Dear Alex,

It is somewhat challenging to compile it for Python 3.5 on Windows (some technical nasty details). But I'll look into it.

However, I have made available an igraph binary on Anaconda for Python 3.6 for Windows, see https://anaconda.org/vtraag/python-igraph. You should be able to use that in Anaconda, although I'm not sure if you'd be able to use that outside of Anaconda. 

Best,

Vincent

**Comment by falexwolf** [comment]
OK, great! That's perfect that. No need for python 3.5 then. Anaconda does the job for us.

Why don't you consider linking to this binary from the python-igraph website? The installation instructions there only link to Christoph Gohlke's website. I'm sure they are happy to link to the anaconda binary installer as well. :smile:

**Comment by falexwolf** [comment]
Playing around with your Anaconda packages, I noticed that for MacOS, you only provide louvain v0.5.3, but for Linux and Windows v0.6. I don't know whether this on purpose. :wink:

**Comment by vtraag** [comment]
OK, good to hear the Anaconda distribution works for you!

The MacOS version for 0.6.1 is not missing on purpose. But I don't have a Mac myself, so I've always needed to rely on others to compile it for me. :) But the package is actually also included in conda-forge: https://anaconda.org/conda-forge/louvain, and does provide the MacOS version for 0.6.1, if you're interested.

Thanks for suggesting mentioning the Anaconda distribution in the python-igraph documentation, I'll look into it.

**Comment by falexwolf** [comment]
Thank you! You could also simply mention it in your own readme and not only state "For Windows: download the binary installers.". :wink:

**Comment by vtraag** [comment]
Haha, true... and a lot easier :smile:

**Comment by cgohlke** [comment]
FWIW, I updated the wheels for [python-igraph](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph) and [louvain-igraph](https://www.lfd.uci.edu/~gohlke/pythonlibs/#louvain-igraph).

**Comment by vtraag** [comment]
Thanks @cgohlke ! Good to hear they're also available from your site, I'll be sure to mention it in the documentation.

**Comment by rmbw51** [comment]
I am using Anaconda 3.7. When tying to install Louvain I get a BIG list of packages to be re-installed, superseded, downgraded etc. Any idea? Many thanks
PS probably because this version is for a previous release?

**Comment by vtraag** [comment]
It depends a bit on your platform, but essentially, yes, that will be the problem. This package will no longer be updated, it has been superseded by https://github.com/vtraag/leidenalg. Please try to install that. If you have problems with that package, please open an issue there.

**Comment by rmbw51** [comment]
yes, done, works very well... will use that from now on. Many thanks

**Comment by vtraag** [comment]
Perfect, good to hear! The documentation for the `leidenalg` package does include a reference to Anaconda, so I am closing this issue.

**Comment by rmbw51** [comment]
yes, installed with the Anaconda installer. all ok
