### ISSUE TITLE
Implementation of new method in Windows

### ISSUE THREAD

**Issue by kevinraja1001** [vtraag/louvain-igraph#30]
I have installed this Louvain implementation using binary installer from https://www.lfd.uci.edu/~gohlke/pythonlibs/ on my Windows 64 bit OS and Python 2.7. I am interested to make a little improvement for my project. I want to add a new class in the source code. I have read your documentation, but I have no idea for where I can put the new class on Windows 64 bit OS platform. In site-packages where the source code being saved, there are only some python files (__init__.py, _version.py, functions.py, Optimiser.py, VertexPartition.py) and _c_louvain.pyd. Please help

**Comment by vtraag** [comment]
It depends what type of change you want to make. The core of the algorithm is implemented in `C++`, but as you noticed, some minor parts are implemented in Python. Compiling `C++` code on Windows is a headache, so I would recommend to use some other platform for that (e.g. Ubuntu or Mac OS). Changing only the Python code requires no compilation, so you should be able to do that more easily. Still, development is probably going to be easier under a different platform. 

To make your own changes, clone the source code and make changes as you see fit. Even easier would be to fork the project to create your own repository of the code and work on that. If you have any changes that would be helpful to the project we could then later integrate those changes in this repository again.

**Comment by kevinraja1001** [comment]
I just want to add limitation on community search (diff_move()) and community assignment. This modification is based on conference paper from Ryu and Kim (2017). I just want to implement it for my final project and thesis. I have a problem in another part of my project (not from this Louvain implementation) when using Ubuntu. 
Is the modification can be done on Anaconda for Windows?

**Comment by vtraag** [comment]
In principle it should work to develop and compile on Windows, see https://wiki.python.org/moin/WindowsCompilers for the required compilers for different versions of Python. I believe Anaconda automatically installs and selects the correct compiler, so that should be somewhat easier. Out of curiosity: I can't find the paper Ryu & Kim (2017) you refer to immediately. Do you have a link?

**Comment by kevinraja1001** [comment]
Thank you. I'll try it using Anaconda.
Here is the link https://ieeexplore.ieee.org/document/7828546/

**Comment by vtraag** [comment]
Thanks!
