### ISSUE TITLE
provide a seed argument to the Optimiser function

### ISSUE THREAD

**Issue by Xiaojieqiu** [vtraag/louvain-igraph#40]
Thanks for this great package! I found the louvain clustering gives different clustering result sometimes with the same parameters. I believe this is because louvain clustering requires random seeding. I wonder whether you can provide an argument to explicitly set the seed for the `Optimiser` function so that the users can get consistent results every time they run if they pass a seed?

**Comment by vtraag** [comment]
Thank you! Please see https://louvain-igraph.readthedocs.io/en/latest/reference.html#louvain.set_rng_seed for the seed. But you are right, it would make more sense if this were in the Optimiser class.

**Comment by Xiaojieqiu** [comment]
thanks for your quick response. I saw the set_rng_seed function but didn't recognize that directly affects seeding in optimiser class. Maybe just a little more documentation will be enough instead of moving that into the optimiser class

**Comment by vtraag** [comment]
Thanks for the suggestion, I'll think about the solution.

**Comment by vtraag** [comment]
Is now implemented.
