### ISSUE TITLE
Weighted modularity not correct?

### ISSUE THREAD

**Issue by dafnevk** [vtraag/louvain-igraph#41]
I noticed louvain-igraph gave different modularity values than I expected, and I found a small example where it seems the package is not taking the weights into account:

```python
import igraph
import louvain
import numpy as np

A = np.array([[ 0.,  2.,  2.,  0.,  0.,  0.],
       [ 2.,  0.,  2.,  0.,  0.,  0.],
       [ 2.,  2.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  2.,  2.],
       [ 0.,  0.,  0.,  2.,  0.,  2.],
       [ 0.,  0.,  0.,  2.,  2.,  0.]])

g = igraph.Graph()
g.add_vertices(len(A))
ix, jx = A.nonzero()
for i,j in zip(ix, jx):
    if i<j:
        g.add_edge(i, j, weight=A[i,j])

part = louvain.find_partition(g, louvain.ModularityVertexPartition, weights='weight')
print(part.membership)
print(part.modularity)
```
Gives output: 
```
[0, 0, 0, 1, 1, 1]
0.357142857142857
```

With my own calculations, as well as through other implementations, I find an (optimal) modularity value of 0.423 for this partiton. The modularity value of 0.357 is valid for the non-weighted equivalent of the graph.

Am I overlooking something or is this a bug in the code?

**Comment by vtraag** [comment]
Thank, I'll look into it! The code is tested on weighted graphs, so in principle it should work. I'm not sure what is going on here, I'll have to take a closer look.

**Comment by vtraag** [comment]
Initially, I overlooked it, but you are looking at the modularity that is provided by `igraph` by default. This is indeed an unweighted variant. To get the quality value of the partition, you should call `part.quality()`, which does provide the corrected weighted modularity. The confusion is understandable, I'll see if I can remove the `modularity` variable in some way.

**Comment by vtraag** [comment]
The modularity variable cannot be removed easily, and it would also create an inconsistency with the existing API from `igraph`, so I am leaving it as is. So, to get the quality of the partition, you always have to call `partition.quality()`, also when using `louvain.ModularityVertexPartition`.
