### ISSUE TITLE
Weighted graph parameter

### ISSUE THREAD

**Issue by ShobiStassen** [vtraag/louvain-igraph#45]
Hi, I was wondering whether you need to explicitly pass a list of weights into the function: louvain.find_partition(G, louvain.ModularityVertexPartition, weights = list_weights) 
or whether you can first construct a weighted graph in igraph and pass this directly into find_partition: 
e.g. 
G_sim = ig.Graph(list(new_edgelist), edge_attrs={'weight': sim_list_new})
partitions = louvain.find_partition(G_sim, louvain.ModularityVertexPartition)  
Thank you

**Comment by vtraag** [comment]
You do have to indicate to use weights, but you can simply refer to the edge attribute:
```python
louvain.find_partition(G, louvain.ModularityVertexPartition, weights = 'weight')
```
This uses `G.es['weight']` as weights.

**Comment by ShobiStassen** [comment]
ah okay got it, thank you for the fast response. 
Is your implementation of the random sampling method (2015 paper) to speed up the original louvain algo available in this package?

**Comment by vtraag** [comment]
Yes, that is also implemented, use this setting to indicate your preference.
