### ISSUE TITLE
"library not found for -lSystem" on mac due to old gcc via brew

### ISSUE THREAD

**Issue by ryan-williams** [vtraag/louvain-igraph#47]
(noting an issue I faced while installing)

I was seeing this error from `pip install louvain` on macOS:

```
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
```

Turns out I had an old version of `gcc` linked in `brew`:

```
$ ls -l /usr/local/bin/g++*
lrwxr-xr-x 1 … /usr/local/bin/g++ -> g++-4.9
lrwxr-xr-x 1 … /usr/local/bin/g++-4.9 -> ../Cellar/gcc@4.9/4.9.4_1/bin/g++-4.9
lrwxr-xr-x 1 … /usr/local/bin/g++-7 -> ../Cellar/gcc@7/7.4.0/bin/g++-7
lrwxr-xr-x 1 … /usr/local/bin/g++-8 -> ../Cellar/gcc/8.3.0/bin/g++-8
```

This fixed it:
```
sudo ln -sf /usr/local/bin/g++-8 /usr/local/bin/g++
```

**Comment by vtraag** [comment]
Thanks for the issue and fix!

Note that this package is deprecated. You probably want to check out the new package https://github.com/vtraag/leidenalg. Most likely the same issue and fix will apply there. But if this does not work, let me know!
