### ISSUE TITLE
issue installing louvain due to new naming of igraph?

### ISSUE THREAD

**Issue by laurenleesc** [vtraag/louvain-igraph#48]
I'm very new at this.  I attempted to install louvain with pip and got the error "Cannot find the C core of igraph on this system...." I updated the path in the setup.py file and it still isn't working.  I noticed that the error script is referring to igraph as 'python-igraph', though my installation in the Anaconda3 Lib is igraph.  Is there a name mismatch? Thanks.  This happened on both of my Windows machines (Windows 10 and Windows 7).

**Comment by vtraag** [comment]
You should be able to install `python-igraph` and `louvain-igraph` from Anaconda using
```
conda install -c vtraag python-igraph louvain-igraph
```

Note that the `louvain-igraph` package is deprecated in favour of the [`leidenalg`](https://github.com/vtraag/leidenalg) package.

**Comment by laurenleesc** [comment]
Thanks! conda install -c vtraag python-igraph leidenalg worked for me.
