### ISSUE TITLE
problem with running the code using ANACONDA

### ISSUE THREAD

**Issue by samah-mo** [vtraag/louvain-igraph#50]
Hello,
I am new to python, I downloaded the code from git hub on windows 10, when I run the code and I got the following error
![image](https://user-images.githubusercontent.com/57817994/68984312-6c77fd00-0820-11ea-9340-e13f9f22f1e5.png)
could you please tell me how to solve that?

**Comment by vtraag** [comment]
It is not possible to simply download the code from GitHub and use it on Windows. If first need to be compiled, but compilation of code on Windows can be quite challenging. You are highly recommended to install directly from Anaconda using `conda install -c vtraag louvain`.

Having said that, I would also recommend switching to the Leiden algorithm https://github.com/vtraag/leidenalg

**Comment by sajaddp** [comment]
Dear @vtraag,
Is it compatible with Python 3.7?
I try to install with `conda install -c vtraag louvain` on windows 64bit nad got this error:
```
Specifications:

  - louvain -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.7
```

**Comment by vtraag** [comment]
Recently, `python-igraph` became available from Windows from the `conda-forge` channel. I plan to update `louvain-igraph` so that it becomes available from the `conda-forge` channel also for Windows. Hopefully I will find some time shortly to do that.
