### ISSUE TITLE
`louvain.set_rng_seed` throws error in current release

### ISSUE THREAD

**Issue by ivirshup** [vtraag/louvain-igraph#54]
It looks like the current version of louvain has a bug in the `set_rng_seed` function:

```python
import louvain
print(louvain.__version__)
# 0.6.2
louvain.set_rng_seed(1)
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/isaac/miniconda3/envs/louvain-install/lib/python3.7/site-packages/louvain/functions.py", line 25, in set_rng_seed
    _c_louvain._set_rng_seed(seed)
AttributeError: module 'louvain._c_louvain' has no attribute '_set_rng_seed'
```

Previously reported here: https://github.com/theislab/scanpy/issues/1191

**Comment by vtraag** [comment]
Thanks for reporting it! I thought it was already changed previously to work similarly to the `leidenalg` package. That is, the seed should be set on the `Optimiser` object (or in `find_partition`). It seems that this was not properly finished, I'll have a look at it shortly.

**Comment by vtraag** [comment]
@ivirshup, could you check if this solves your issue? You would have to change this line

https://github.com/theislab/scanpy/blob/127c8b2ce9aecee00d2b42118a1b343e1e51555b/scanpy/tools/_louvain.py#L144

dependent on the version of `louvain`, and for the new version you should pass it as a parameter to `find_partition` (or to the `Optimiser` object). I will make a new proper release 0.7.0, to indicate it is incompatible with version 0.6.x and yank version 0.6.2. You could then either test for the existence of `louvain.set_rng_seed` or test the version of the package.

**Comment by ivirshup** [comment]
That looks like it'll work. 

I'm having trouble checking since I'm not sure how to install a development version of this library. I'm happy to take your word for it though, and checking when there's a new release.

**Comment by vtraag** [comment]
OK, I will start preparing a release.

FWIW, you can download binary wheels for all platforms from the current CI build, see https://ci.appveyor.com/project/vtraag/louvain-igraph, under "artifacts" for each job. The macOS version is now rebuilding, for some reason that job was terminated.
