### ISSUE TITLE
How should I assign weights to different layers when doing community detection?

### ISSUE THREAD

**Issue by chansigit** [vtraag/louvain-igraph#63]
Dear author,
I am performing community detection on a multiplex network (same sets of nodes, different layers, no inter-layer edges)

I hope to assign different weights to different layers so that some node types of edges could be more important in the community formation. 

How can I achieve this in "find_partition_multiplex"? I failed to find the answer from the doc. 

Looking forward to your answer.

Thanks!

**Comment by vtraag** [comment]
For anyone interested, this was cross-posted, and answered, in the `leidenalg` package here: https://github.com/vtraag/leidenalg/issues/128.
