### ISSUE TITLE
Support python-igraph 0.11

### ISSUE THREAD

**Issue by szhorvat** [vtraag/louvain-igraph#66]
Can we please have an update to support py-igraph 0.11 here as well?

**Comment by szhorvat** [comment]
To be clear, the change has already been made, see #65. All we need as a release. There are single cell genomics packages which use this, and they won't upgrade to python-igraph 0.11 until louvain-igraph supports it. This then has a ripple effect through the package dependency graph, holding back a potentially large portion of our userbase.

**Comment by vtraag** [comment]
Tagged the latest version, should be on its way to PyPI if CI goes well (as is expected).
